api_platform:
  patch_formats:
    json: [ 'application/merge-patch+json' ]
  title: 'API IN MARKETIFY'
  description: 'API IN MARKETIFY PLATFORM'
  version: '1.0.0'
  show_webby: false
  #Enable the Swagger documentation and export.
  enable_swagger: true
  eager_loading:
    # To enable or disable eager loading.
    enabled: false
    # If disabled, it will only join relations having the EAGER fetch mode.
    force_eager: false
    max_joins: 100
    fetch_partial: true
  mapping:
    paths:
      - '%kernel.project_dir%/src/Entity/Main'
      - '%kernel.project_dir%/src/Entity/Master'
      - '%kernel.project_dir%/src/Entity/Commerce'
  swagger:
    versions: [ 3 ]
